# -*- mode: python ; coding: utf-8 -*-

import sys
import os
from pathlib import Path

# 当前目录（lastMusic）
root_dir = Path(os.path.abspath("."))

a = Analysis(
    ["app/main.py"],
    pathex=[str(root_dir)],
    binaries=[],
    datas=[
        # 所有 Python 包
        (str(root_dir / "app"), "app"),

        # spiders 目录（encrypt.py + RSA.js，netease.py 依赖它们）
        (str(root_dir / "spiders"), "spiders"),

        # 上传资源（默认封面）
        (str(root_dir / "uploads"), "uploads"),

        # 数据库迁移
        (str(root_dir / "alembic"), "alembic"),
        (str(root_dir / "alembic.ini"), "."),
    ],
    hiddenimports=[
        "app.main",
        "app.api",
        "app.api.v1",
        "app.api.v1.auth",
        "app.api.v1.users",
        "app.api.v1.songs",
        "app.api.v1.artists",
        "app.api.v1.albums",
        "app.api.v1.lyric",
        "app.api.v1.comments",
        "app.api.v1.playlists",
        "app.api.v1.favorites",
        "app.api.v1.follow",
        "app.api.v1.message",
        "app.api.v1.search",
        "app.api.v1.network_search",
        "app.api.v1.ranking",
        "app.api.v1.recommend",
        "app.api.v1.health",
        "app.core",
        "app.core.config",
        "app.core.database",
        "app.core.redis_client",
        "app.core.redis_keys",
        "app.core.cache",
        "app.core.deps",
        "app.models",
        "app.models.users",
        "app.models.user_details",
        "app.models.songs",
        "app.models.artists",
        "app.models.albums",
        "app.models.lyrics",
        "app.models.playlists",
        "app.models.comments",
        "app.models.messages",
        "app.models.play_history",
        "app.models.search_history",
        "app.models.user_follow_user",
        "app.models.user_follow_artist",
        "app.models.user_save_song",
        "app.models.user_save_album",
        "app.models.user_save_playlist",
        "app.models.user_like_comment",
        "app.models.artist_sing_song",
        "app.models.playlist_save_song",
        "app.models.album_save_song",
        "app.models.base",
        "app.schemas",
        "app.schemas.common",
        "app.schemas.user",
        "app.schemas.song",
        "app.schemas.artist",
        "app.schemas.album",
        "app.schemas.comment",
        "app.schemas.message",
        "app.schemas.lyric",
        "app.schemas.playlist",
        "app.schemas.favorite",
        "app.services",
        "app.services.song_service",
        "app.services.network_search_service",
        "app.services.network_search_service.base",
        "app.services.network_search_service.netease",
        "app.utils",
        "app.utils.security",
        # 额外 hidden imports（解决 FastAPI 的延迟导入）
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "multipart",
        "bcrypt",
        "jose",
        "jose.backends",
        "httpx",
        "sqlalchemy",
        "sqlalchemy.ext.asyncio",
        "asyncmy",
        "pydantic",
        "pydantic_settings",
        "alembic",
        "Crypto",
        "Crypto.Cipher",
        "Crypto.Util",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "PIL.ImageShow",
        "PIL.ImageQt",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="myMusic",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
